### ISSUE TITLE
"Lost sync with device" problem

### ISSUE THREAD

**Issue by XiaoweiLinXL** [sachin0x18/rosserial_esp32#4]
I found your question about "ESP32 + rosserial_python over WiFi: Lost sync with device", I wonder how did you fix this problem? I am now using STM32 and rosserial package and facing the same problem. Thank you!

**Comment by sachin0x18** [comment]
This problem could occur due to multiple reasons.

One reason could be that you are not calling `nh.spinOnce()` regularly.
Another reason (the one I encountered) was that the sockets were blocking. Configuring the sockets as non blocking solves this issue.

You can find the fix here: 
https://github.com/sachin0x18/rosserial_esp32/blob/78e82edd2e1b0bbf1a65fa7a12042e2e111c8770/src/ros_lib/esp_ros_wifi.c#L113

**Comment by XiaoweiLinXL** [comment]
What do you mean by calling `nh.spinOnce()` regularly, I have a loop function in my `main.c` looping every 10ms, how do I know if I am calling it regularly?

**Comment by sachin0x18** [comment]
You can go through the ROS tutorials (http://wiki.ros.org/rosserial_arduino/Tutorials/Hello%20World) and understand the anatomy of the code. You can then apply it for STM32

**Comment by XiaoweiLinXL** [comment]
Okay, thank you so much!
